In [2]:
import numpy as np
n=np.arange(27)
n

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

In [3]:
n.reshape(3,3,3)

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [4]:
my_list=[[1,2,345,6],[]]
n=np.asarray(my_list)
n

array([list([1, 2, 345, 6]), list([])], dtype=object)

In [5]:
import cv2
im_g=cv2.imread("img\\smallgray.png", 0)
im_g

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)

In [6]:
im_g2=cv2.imread("img\\smallgray.png", 1)
im_g2

array([[[187, 187, 187],
        [158, 158, 158],
        [104, 104, 104],
        [121, 121, 121],
        [143, 143, 143]],

       [[198, 198, 198],
        [125, 125, 125],
        [255, 255, 255],
        [255, 255, 255],
        [147, 147, 147]],

       [[209, 209, 209],
        [134, 134, 134],
        [255, 255, 255],
        [ 97,  97,  97],
        [182, 182, 182]]], dtype=uint8)

In [7]:
cv2.imwrite("img\\newpicture.png", im_g)

True

In [8]:
im_g[0:2, 2:4]

array([[104, 121],
       [255, 255]], dtype=uint8)

In [9]:
for i in im_g:
    print(i)
print()
for i in im_g.T:
    print(i)
print()
for i in im_g.flat:
    print(i)

[187 158 104 121 143]
[198 125 255 255 147]
[209 134 255  97 182]

[187 198 209]
[158 125 134]
[104 255 255]
[121 255  97]
[143 147 182]

187
158
104
121
143
198
125
255
255
147
209
134
255
97
182


In [12]:
ims = np.hstack((im_g, im_g))
ims

array([[187, 158, 104, 121, 143, 187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147, 198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182, 209, 134, 255,  97, 182]], dtype=uint8)

In [16]:
ims = np.vstack((im_g, im_g))
ims

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182],
       [187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)

In [19]:
ims=np.hsplit(im_g, 5)
print(ims)

[array([[187],
       [198],
       [209]], dtype=uint8), array([[158],
       [125],
       [134]], dtype=uint8), array([[104],
       [255],
       [255]], dtype=uint8), array([[121],
       [255],
       [ 97]], dtype=uint8), array([[143],
       [147],
       [182]], dtype=uint8)]


In [23]:
ims=np.vsplit(im_g, 3)
ims

[array([[187, 158, 104, 121, 143]], dtype=uint8),
 array([[198, 125, 255, 255, 147]], dtype=uint8),
 array([[209, 134, 255,  97, 182]], dtype=uint8)]